# Generated by Django 4.2.17 on 2025-01-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardcategory',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='boardcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='boardcategory',
            table='board_category',
        ),
    ]
