# Generated by Django 4.2.17 on 2025-01-05 13:19

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.category_image_upload_path),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
