# Generated by Django 4.2.17 on 2025-01-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_image_alter_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content_type',
            field=models.CharField(default='default_content', max_length=255),
        ),
    ]
