# Generated by Django 4.2.17 on 2025-01-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content_type',
            field=models.CharField(default='글', max_length=255),
        ),
    ]
