# Generated by Django 4.2.17 on 2025-01-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='products/headers/')),
                ('detail_image', models.ImageField(upload_to='products/details/')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('price_detail', models.TextField()),
                ('origin', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('is_free_shipping', models.BooleanField(default=False)),
                ('is_admin_recommended', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
        ),
    ]
