# Generated by Django 4.2.17 on 2025-01-12 08:44

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_image',
            field=models.ImageField(upload_to=shop.models.safe_file_upload_path_details),
        ),
        migrations.AlterField(
            model_name='product',
            name='header_image',
            field=models.ImageField(upload_to=shop.models.safe_file_upload_path_headers),
        ),
    ]
