# Generated by Django 4.2.17 on 2025-01-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_group_id',
            field=models.CharField(max_length=100),
        ),
    ]
